[package]
name = "sql-splitter"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.32", features = ["full"] }
clap = { version = "4.4", features = ["derive"] }
futures = "0.3"

[dev-dependencies]
tempfile = "3.8"